---
title: "Final Project"
output: pdf_document
---
---
title: "NISPUF"
output: pdf_document
date: '2022-04-03'
---
```{r}
############################################################################
# PROGRAM:  NISPUF20.R                                                     #
#                                                                          #
# PURPOSE:  THIS R PROGRAM CREATES A PERMANENT R DATASET                   #
#           FROM THE 2020 NIS PUBLIC-USE ASCII FILE                        #
#                                                                          #
# NOTES:    THIS PROGRAM IS DIVIDED INTO SEVEN STEPS AS FOLLOWS:           #
#                                                                          #
# STEP 1:   LOAD AN R PACKAGE AND ASSIGN FILE NAMES                        #
#                                                                          #
#		 ONE R PACKAGE FOR TWO FUNCTIONS (CONTENTS, WTD.TABLE)                 #
#		 WILL BE LOADED	                                                       #
#		 THE USER CAN ENTER THE PATH TO THE ASCII DATA FILE AND                #
#		 THE PATH WHERE THE R DATASET WILL BE CREATED                          #
#                                                                          #
# STEP 2:   CREATE FORMATS                                                 #
#                                                                          #
# STEP 3:   READ THE FLAT DATA FILE                                        #
#                                                                          #
# STEP 4:   ASSIGN VARIABLE LABELS                                         #
#                                                                          #
# STEP 5:   CREATE A PERMANENT R DATASET                                   #
#                                                                          #
# STEP 6:   ASSIGN FORMATS                                                 #
#                                                                          #
#	   FORMATS ARE APPLICABLE ONLY TO CATEGORICAL VARIABLES IN R    	       #
#                                                                          #
# STEP 7:   CONTENTS AND STATISTICAL ESTIMATES(FREQUENCY) EXAMPLE          #
#                                                                          #
############################################################################

############################################################################
# Step 1:   LOAD R PACKAGES AND ASSIGN FILE NAMES                          #
############################################################################
#Users may need to install the Hmisc library before invoking it.
library(Hmisc) #TO USE contents()

#---USE SLASH(/) TO SEPERATE A FILE PATH---#
PUF <- "/Users/laurenmitchell/Downloads"

flatfile <- "/Users/laurenmitchell/Downloads/NISPUF20.DAT"



############################################################################
# Step 2:   CREATE FORMATS                                                 #
############################################################################

AGEGRPlevels=c(1,2,3)
AGEGRPlabels=c("19 - 23 MONTHS", "24 - 29 MONTHS", "30 - 35 MONTHS")

LANGUAGElevels=c(1,2,3)
LANGUAGElabels=c("ENGLISH", "SPANISH", "OTHER")

YNDKRFlevels=c(1,2,77,99)
YNDKRFlabels=c("YES", "NO", "DON'T KNOW", "REFUSED")

YNlevels=c(1,2)
YNlabels=c("YES", "NO")

Ylevels=c(1)
Ylabels=c("YES")

CHILDNMlevels=c(1,2,3,77,99)
CHILDNMlabels=c("ONE", "TWO OR THREE", "FOUR OR MORE", "DON'T KNOW", "REFUSED")

CWIClevels=c(1,2,3,77,99)
CWIClabels=c("YES", "NO", "NEVER HEARD OF WIC", "DON'T KNOW", "REFUSED")

EDUC1_levels=c(1,2,3,4,77,99)
EDUC1_labels=c("< 12 YEARS", "12 YEARS", "> 12 YEARS, NON-COLLEGE GRAD", "COLLEGE GRAD", "DON'T KNOW", "REFUSED")

HISPlevels=c(1,2,3,4,5)
HISPlabels=c("HISPANIC", "NON-HISPANIC", "OTHER", "DON'T KNOW", "REFUSED")

MOBILlevels=c(1,2,77,99)
MOBILlabels=c("MOVED FROM DIFFERENT STATE", "DID NOT MOVE FROM DIFFERENT STATE", "DON'T KNOW", "REFUSED")

SEXlevels=c(1,2,77,99)
SEXlabels=c("MALE", "FEMALE", "DON'T KNOW", "REFUSED")

INCPOVlevels=c(1,2,3,4)
INCPOVlabels=c("ABOVE POVERTY, > $75K", "ABOVE POVERTY, <= $75K", "BELOW POVERTY", "UNKNOWN")

HASPDA2Flevels=c(1,2)
HASPDA2Flabels=c("CHILD HAS ADEQUATE PROVIDER DATA OR ZERO VACCINATIONS", "CHILD DOES NOT HAVE ADEQUATE PROVIDER DATA")

PROVIDlevels=c(1,2,3,4,5,6,7)
PROVIDlabels=c("ALL PUBLIC FACILITIES", "ALL HOSPITAL FACILITIES", "ALL PRIVATE FACILITIES", "ALL MILITARY/OTHER FACILITIES", "MIXED", "TYPE OF PROVIDER UNKNOWN", "ALL WIC CLINIC PROVIDERS")

REGISTRYlevels=c(1,2,3,4)
REGISTRYlabels=c("ALL PROVIDERS", "SOME BUT POSSIBLY OR DEFINITELY NOT ALL PROVIDERS", "NO PROVIDERS", "UNKNOWN/DON'T KNOW")

TYPElevels=c("","01","02","03","04","05","07","08","1L","1M","1N","20","21","22","30","31","32","33","43","44","60","70","71","72","73","74","BC","D3","DH","DK","FL","FM","FN","FO","H2","HA","HB","HG","HI","HM","HS","HY","MA","MB","MM","MP","NC","OT","RB",
"RG","RM","RO","TY","UN","VA","VM","VO","YF")
TYPElabels=c("MISSING", "DT", "DTP", "DTP-UNKNOWN", "DTAP", "DTP-HIB", "DTAP-HIB", "DTAP-HEPB-IPV", "H1N1 FLU-UNKNOWN", "H1N1 FLU SPRAY", "H1N1 FLU INJECTED", "OPV", "IPV", "POLIO-UNKNOWN", "MMR", "MEASLES ONLY", "MEASLES-MUMPS", "MEASLES-RUBELLA",
"HEPB-HIB", "HIB ONLY-UNKNOWN", "HEPB ONLY", "PCV CONJUGATE-UNKNOWN", "PCV POLYSACCHARIDE", "PCV-UNKNOWN", "PCV CONJUGATE-7", "PCV CONJUGATE-13", "BCG (TUBERCULOSIS)", "DTAP-IPV-HIB", "DTP-HEPB", "DON'T KNOW", "SEASONAL FLU-UNKNOWN", "SEASONAL FLU SPRAY",
"SEASONAL FLU INJECTED", "FOUR-IN-ONE", "HIB (SANOFI OR GLAXOSMITHKLINE)", "HEPA", "HEPB-UNKNOWN", "HIB (GLAXOSMITHKLINE)", "HIB-UNKNOWN", "HIB (MERCK)", "HIB (SANOFI)", "HIB-MENCY", "MALARIA", "MUMPS-RUBELLA", "MCV-UNKNOWN", "MUMPS", "NEVER CODABLE",
"OTHER", "RUBELLA", "ROTARIX (GSK)", "ROTATEQ (MERCK)", "ROTAVIRUS-UNKNOWN", "TYPHOID", "UNCODABLE", "VARICELLA-UNKNOWN", "MMR-VARICELLA", "VARICELLA-ONLY", "YELLOW FEVER")

HEPBRTlevels=c(1,2)
HEPBRTlabels=c("AT LEAST ONE PROVIDER CHECKED GIVEN AT BIRTH", "NO PROVIDERS CHECKED GIVEN AT BIRTH")

HEPFLGlevels=c(1,2)
HEPFLGlabels=c("HEPB BIRTH SHOT DATE IMPUTED FROM SHOTCARD", "HEPB BIRTH SHOT DATE IMPUTED FROM DISTRIBUTION OF BIRTH DOSE DATES")

UTDlevels=c(0,1)
UTDlabels=c("NOT UTD", "UTD")

CENREGlevels=c(1,2,3,4)
CENREGlabels=c("NORTHEAST", "MIDWEST", "SOUTH", "WEST")

STATElevels=c(1,10,11,12,13,15,16,17,18,19,2,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,4,40,41,42,44,45,46,47,48,49,5,50,51,53,54,55,56,6,66,72,78,8,9)
STATElabels=c("ALABAMA", "DELAWARE", "DISTRICT OF COLUMBIA", "FLORIDA", "GEORGIA", "HAWAII", "IDAHO", "ILLINOIS", "INDIANA", "IOWA", "ALASKA", "KANSAS", "KENTUCKY", "LOUISIANA", "MAINE", "MARYLAND", "MASSACHUSETTS", "MICHIGAN", "MINNESOTA", "MISSISSIPPI",
"MISSOURI", "MONTANA", "NEBRASKA", "NEVADA", "NEW HAMPSHIRE", "NEW JERSEY", "NEW MEXICO", "NEW YORK", "NORTH CAROLINA", "NORTH DAKOTA", "OHIO", "ARIZONA", "OKLAHOMA", "OREGON", "PENNSYLVANIA", "RHODE ISLAND", "SOUTH CAROLINA", "SOUTH DAKOTA", "TENNESSEE",
"TEXAS", "UTAH", "ARKANSAS", "VERMONT", "VIRGINIA", "WASHINGTON", "WEST VIRGINIA", "WISCONSIN", "WYOMING", "CALIFORNIA", "GUAM", "PUERTO RICO", "U.S.  VIRGIN ISLANDS", "COLORADO", "CONNECTICUT")

RACE_PUFlevels=c(1,2,3)
RACE_PUFlabels=c("WHITE ONLY", "BLACK ONLY", "OTHER + MULTIPLE RACE")

AGECPOXRlevels=c(1,2,3,4)
AGECPOXRlabels=c("0 TO 6 MONTHS OLD", "7 TO 12 MONTHS OLD", "13 TO 18 MONTHS OLD", "19+ MONTHS OLD")

C1Rlevels=c(1,2,3,4,5,6,7,8)
C1Rlabels=c("1", "2", "3", "4", "5", "6", "7", "8+")

C5Rlevels=c(1,2,3,4,77,99)
C5Rlabels=c("MOTHER (STEP, FOSTER, ADOPTIVE) OR FEMALE GUARDIAN", "FATHER (STEP, FOSTER, ADOPTIVE) OR MALE GUARDIAN", "GRANDPARENT", "OTHER FAMILY MEMBER/FRIEND", "DON'T KNOW", "REFUSED")

INCQ298Alevels=c(10,11,12,13,14,3,4,5,6,7,77,8,9,99)
INCQ298Alabels=c("$35001 - $40000", "$40001 - $50000", "$50001 - $60000", "$60001 - $75000", "$75001+", "$0 - $7500", "$7501 - $10000", "$10001 - $17500", "$17501 - $20000", "$20001 - $25000", "DON'T KNOW", "$25001 - $30000", "$30001 - $35000", "REFUSED")

RACEETHKlevels=c(1,2,3,4)
RACEETHKlabels=c("HISPANIC", "NON-HISPANIC WHITE ONLY", "NON-HISPANIC BLACK ONLY", "NON-HISPANIC OTHER + MULTIPLE RACE")

D6Rlevels=c(0,1,2,3)
D6Rlabels=c("0", "1", "2", "3+")

FRSTBRNlevels=c(1,2,77,99)
FRSTBRNlabels=c("NO", "YES", "DON'T KNOW", "REFUSED")

RENTOWNlevels=c(1,2,3,77,99)
RENTOWNlabels=c("OWNED OR BEING BOUGHT", "RENTED", "OTHER ARRANGMENT", "DON'T KNOW", "REFUSED")

NUM_PHONlevels=c(1,2,3,4,77,99)
NUM_PHONlabels=c("ONE", "TWO", "THREE OR MORE", "NONE", "DON'T KNOW", "REFUSED")

MAR_PUF2_levels=c(1,2)
MAR_PUF2_labels=c("MARRIED", "NEVER MARRIED/WIDOWED/DIVORCED/SEPARATED/DECEASED/LIVING WITH PARTNER")

UTDPCVBlevels=c(1,2,3)
UTDPCVBlabels=c("4+ PCV7 PLUS 1+ PCV13", "4+ PCV7, NO FOLLOWING PCV13, WITH TYPE OF ALL VACCINES (IF ANY) FOLLOWING THE 4 PCV7 KNOWN", "ALL OTHERS WITH ADEQUATE PROVIDER DATA")

ESTGRANTlevels=c(1,10,11,12,13,14,16,17,18,19,2,20,22,25,27,28,29,30,31,34,35,36,38,4,40,41,44,46,47,49,5,50,51,54,55,56,57,58,59,6,60,61,62,63,64,65,66,68,7,72,73,74,75,76,77,8)
ESTGRANTlabels=c("CT", "NY-REST OF STATE", "NY-CITY OF NEW YORK", "DC", "DE", "MD", "PA-REST OF STATE", "PA-PHILADELPHIA COUNTY", "VA", "WV", "MA", "AL", "FL", "GA", "KY", "MS", "NC", "SC", "TN", "IL-REST OF STATE", "IL-CITY OF CHICAGO", "IN", "MI", "ME",
"MN", "OH", "WI", "AR", "LA", "NM", "NH", "OK", "TX-REST OF STATE", "TX-CITY OF HOUSTON", "TX-BEXAR COUNTY", "IA", "KS", "MO", "NE", "RI", "CO", "MT", "ND", "SD", "UT", "WY", "AZ", "CA", "VT", "HI", "NV", "AK", "ID", "OR", "WA", "NJ")

INS_BREAK_Ilevels=c(1,2,3,4)
INS_BREAK_Ilabels=c("CURRENTLY INSURED BUT UNINSURED AT SOME POINT SINCE BIRTH", "CURRENTLY INSURED AND NEVER UNINSURED SINCE BIRTH", "CURRENTLY UNINSURED BUT INSURED AT SOME POINT SINCE BIRTH",
"CURRENTLY UNINSURED AND NEVER INSURED SINCE BIRTH")

MAGEGRP2_levels=c(1,2,77,99)
MAGEGRP2_labels=c("<= 29 YEARS", ">= 30 YEARS", "DON'T KNOW", "REFUSED")

INS_STAT2_Ilevels=c(1,2,3,4)
INS_STAT2_Ilabels=c("PRIVATE INSURANCE ONLY", "ANY MEDICAID", "OTHER INSURANCE (CHIP, IHS, MILITARY, OR OTHER, ALONE OR IN COMB. WITH PRIVATE INSURANCE)", "UNINSURED")

ESTIAPFlevels=c(1,10,105,106,107,109,11,12,13,14,16,17,18,19,2,20,22,25,27,28,29,30,31,34,35,36,38,4,40,41,44,46,47,49,5,50,51,52,53,54,55,56,57,58,59,6,60,61,62,63,64,65,66,68,7,72,73,74,75,76,77,8,95)
ESTIAPFlabels=c("CT", "NY-REST OF STATE", "GUAM", "PUERTO RICO", "TX-HIDALGO COUNTY", "TX-TARRANT COUNTY", "NY-CITY OF NEW YORK", "DC", "DE", "MD", "PA-REST OF STATE", "PA-PHILADELPHIA COUNTY", "VA", "WV", "MA", "AL", "FL", "GA", "KY", "MS", "NC", "SC",
"TN", "IL-REST OF STATE", "IL-CITY OF CHICAGO", "IN", "MI", "ME", "MN", "OH", "WI", "AR", "LA", "NM", "NH", "OK", "TX-REST OF STATE", "TX-DALLAS COUNTY", "TX-EL PASO COUNTY", "TX-CITY OF HOUSTON", "TX-BEXAR COUNTY", "IA", "KS", "MO", "NE", "RI", "CO",
"MT", "ND", "SD", "UT", "WY", "AZ", "CA", "VT", "HI", "NV", "AK", "ID", "OR", "WA", "NJ", "U.S. VIRGIN ISLANDS")


############################################################################
# Step 3:   READ THE FLAT DATA FILE                                        #
############################################################################

LIST.NAMEWIDTH <-
c("SEQNUMC",6,
"SEQNUMHH",5,
"PDAT",1,
"PROVWT_C",19,
"PROVWT_C_TERR",19,
"RDDWT_C",19,
"RDDWT_C_TERR",19,
"STRATUM",4,
"YEAR",4,
"AGECPOXR",1,
"HAD_CPOX",2,
"AGEGRP",1,
"BF_ENDR06",8,
"BF_EXCLR06",8,
"BF_FORMR20",8,
"BFENDFL06",1,
"BFFORMFL06",1,
"C1R",1,
"C5R",2,
"CBF_01",2,
"CEN_REG",1,
"CHILDNM",1,
"CWIC_01",2,
"CWIC_02",2,
"EDUC1",1,
"FRSTBRN",1,
"I_HISP_K",1,
"INCPORAR",16,
"INCPORAR_I",16,
"INCPOV1",1,
"INCQ298A",2,
"LANGUAGE",1,
"M_AGEGRP2",1,
"MARITAL2",1,
"MOBIL_I",1,
"NUM_PHONE",2,
"NUM_CELLS_HH",2,
"NUM_CELLS_PARENTS",2,
"RACE_K",1,
"RACEETHK",1,
"RENT_OWN",2,
"SEX",1,
"ESTIAP20",3,
"EST_GRANT",2,
"STATE",2,
"D6R",1,
"D7",1,
"N_PRVR",1,
"PROV_FAC",1,
"REGISTRY",1,
"VFC_ORDER",1,
"HEP_BRTH",1,
"HEP_FLAG",1,
"P_NUHEPX",1,
"P_NUHIBX",1,
"P_NUHPHB",1,
"P_NUMDAH",1,
"P_NUMDHI",1,
"P_NUMDIH",1,
"P_NUMDTA",1,
"P_NUMDTP",1,
"P_NUMFLU",1,
"P_NUMFLUL",1,
"P_NUMFLUM",1,
"P_NUMFLUN",1,
"P_NUMHEA",1,
"P_NUMHEN",1,
"P_NUMHEP",1,
"P_NUMHG",1,
"P_NUMHHY",1,
"P_NUMHIB",1,
"P_NUMHIN",1,
"P_NUMHION",1,
"P_NUMHM",1,
"P_NUMHS",1,
"P_NUMIPV",1,
"P_NUMMCN",1,
"P_NUMMMR",1,
"P_NUMMMRX",1,
"P_NUMMMX",1,
"P_NUMMP",1,
"P_NUMMPR",1,
"P_NUMMRV",1,
"P_NUMMS",1,
"P_NUMMSM",1,
"P_NUMMSR",1,
"P_NUMOLN",1,
"P_NUMOPV",1,
"P_NUMPCV",1,
"P_NUMPCP",1,
"P_NUMPCC",1,
"P_NUMPCC7",1,
"P_NUMPCC13",1,
"P_NUMPCCN",1,
"P_NUMPCN",1,
"P_NUMPOL",1,
"P_NUMRB",1,
"P_NUMRG",1,
"P_NUMRM",1,
"P_NUMRO",1,
"P_NUMROT",1,
"P_NUMTPN",1,
"P_NUMVRC",1,
"P_NUMVRN",1,
"P_NUMVRX",1,
"P_U12VRC",1,
"P_UTD331",1,
"P_UTD431",1,
"P_UTDHEP",1,
"P_UTDHEPA1",1,
"P_UTDHEPA2",1,
"P_UTDHIB",1,
"P_UTDHIB_ROUT_S",1,
"P_UTDHIB_SHORT_S",1,
"P_UTDMCV",1,
"P_UTDMMX",1,
"P_UTDPC3",1,
"P_UTDPCV",1,
"P_UTDPCVB13",1,
"P_UTDPOL",1,
"P_UTDROT_S",1,
"P_UTDTP3",1,
"P_UTDTP4",1,
"PU431331",1,
"P_UTD431H31_ROUT_S",1,
"PU4313313",1,
"P_UTD431H313_ROUT_S",1,
"PU4313314",1,
"P_UTD431H314_ROUT_S",1,
"PUT43133",1,
"P_UTD431H3_ROUT_S",1,
"PUTD4313",1,
"P_UTD431H_ROUT_S",1,
"U24_FLU_24D",1,
"U19_FLU_24D",1,
"U24_FLU3_24D",1,
"U1D_HEP",1,
"U2D_HEP",1,
"U3D_HEP",1,
"DDTP1",4,
"DDTP2",4,
"DDTP3",4,
"DDTP4",4,
"DDTP5",4,
"DDTP6",4,
"DDTP7",4,
"DDTP8",1,
"DDTP9",1,
"DFLU1",4,
"DFLU2",4,
"DFLU3",4,
"DFLU4",4,
"DFLU5",4,
"DFLU6",4,
"DFLU7",3,
"DFLU8",1,
"DFLU9",1,
"DHEPA1",4,
"DHEPA2",4,
"DHEPA3",4,
"DHEPA4",3,
"DHEPA5",1,
"DHEPA6",1,
"DHEPA7",1,
"DHEPA8",1,
"DHEPA9",1,
"DHEPB1",4,
"DHEPB2",4,
"DHEPB3",4,
"DHEPB4",4,
"DHEPB5",4,
"DHEPB6",4,
"DHEPB7",4,
"DHEPB8",1,
"DHEPB9",1,
"DHIB1",4,
"DHIB2",4,
"DHIB3",4,
"DHIB4",4,
"DHIB5",3,
"DHIB6",3,
"DHIB7",3,
"DHIB8",1,
"DHIB9",1,
"DMMR1",4,
"DMMR2",4,
"DMMR3",4,
"DMMR4",1,
"DMMR5",1,
"DMMR6",1,
"DMMR7",1,
"DMMR8",1,
"DMMR9",1,
"DMP1",3,
"DMP2",1,
"DMP3",1,
"DMP4",1,
"DMP5",1,
"DMP6",1,
"DMP7",1,
"DMP8",1,
"DMP9",1,
"DMPRB1",1,
"DMPRB2",1,
"DMPRB3",1,
"DMPRB4",1,
"DMPRB5",1,
"DMPRB6",1,
"DMPRB7",1,
"DMPRB8",1,
"DMPRB9",1,
"DPCV1",3,
"DPCV2",4,
"DPCV3",4,
"DPCV4",4,
"DPCV5",4,
"DPCV6",3,
"DPCV7",3,
"DPCV8",1,
"DPCV9",1,
"DPOLIO1",4,
"DPOLIO2",4,
"DPOLIO3",4,
"DPOLIO4",4,
"DPOLIO5",4,
"DPOLIO6",4,
"DPOLIO7",3,
"DPOLIO8",1,
"DPOLIO9",1,
"DRB1",3,
"DRB2",1,
"DRB3",1,
"DRB4",1,
"DRB5",1,
"DRB6",1,
"DRB7",1,
"DRB8",1,
"DRB9",1,
"DROT1",3,
"DROT2",3,
"DROT3",3,
"DROT4",3,
"DROT5",3,
"DROT6",1,
"DROT7",1,
"DROT8",1,
"DROT9",1,
"DVRC1",4,
"DVRC2",4,
"DVRC3",3,
"DVRC4",1,
"DVRC5",1,
"DVRC6",1,
"DVRC7",1,
"DVRC8",1,
"DVRC9",1,
"DTP1_AGE",2,
"DTP2_AGE",2,
"DTP3_AGE",2,
"DTP4_AGE",2,
"DTP5_AGE",2,
"DTP6_AGE",2,
"DTP7_AGE",2,
"DTP8_AGE",1,
"DTP9_AGE",1,
"FLU1_AGE",2,
"FLU2_AGE",2,
"FLU3_AGE",2,
"FLU4_AGE",2,
"FLU5_AGE",2,
"FLU6_AGE",2,
"FLU7_AGE",2,
"FLU8_AGE",1,
"FLU9_AGE",1,
"HEA1_AGE",2,
"HEA2_AGE",2,
"HEA3_AGE",2,
"HEA4_AGE",2,
"HEA5_AGE",1,
"HEA6_AGE",1,
"HEA7_AGE",1,
"HEA8_AGE",1,
"HEA9_AGE",1,
"HEP1_AGE",2,
"HEP2_AGE",2,
"HEP3_AGE",2,
"HEP4_AGE",2,
"HEP5_AGE",2,
"HEP6_AGE",2,
"HEP7_AGE",2,
"HEP8_AGE",1,
"HEP9_AGE",1,
"HIB1_AGE",2,
"HIB2_AGE",2,
"HIB3_AGE",2,
"HIB4_AGE",2,
"HIB5_AGE",2,
"HIB6_AGE",2,
"HIB7_AGE",2,
"HIB8_AGE",1,
"HIB9_AGE",1,
"MMR1_AGE",2,
"MMR2_AGE",2,
"MMR3_AGE",2,
"MMR4_AGE",1,
"MMR5_AGE",1,
"MMR6_AGE",1,
"MMR7_AGE",1,
"MMR8_AGE",1,
"MMR9_AGE",1,
"MP1_AGE",2,
"MP2_AGE",1,
"MP3_AGE",1,
"MP4_AGE",1,
"MP5_AGE",1,
"MP6_AGE",1,
"MP7_AGE",1,
"MP8_AGE",1,
"MP9_AGE",1,
"MPR1_AGE",1,
"MPR2_AGE",1,
"MPR3_AGE",1,
"MPR4_AGE",1,
"MPR5_AGE",1,
"MPR6_AGE",1,
"MPR7_AGE",1,
"MPR8_AGE",1,
"MPR9_AGE",1,
"PCV1_AGE",2,
"PCV2_AGE",2,
"PCV3_AGE",2,
"PCV4_AGE",2,
"PCV5_AGE",2,
"PCV6_AGE",2,
"PCV7_AGE",2,
"PCV8_AGE",1,
"PCV9_AGE",1,
"POL1_AGE",2,
"POL2_AGE",2,
"POL3_AGE",2,
"POL4_AGE",2,
"POL5_AGE",2,
"POL6_AGE",2,
"POL7_AGE",2,
"POL8_AGE",1,
"POL9_AGE",1,
"RB1_AGE",2,
"RB2_AGE",1,
"RB3_AGE",1,
"RB4_AGE",1,
"RB5_AGE",1,
"RB6_AGE",1,
"RB7_AGE",1,
"RB8_AGE",1,
"RB9_AGE",1,
"ROT1_AGE",2,
"ROT2_AGE",2,
"ROT3_AGE",2,
"ROT4_AGE",2,
"ROT5_AGE",2,
"ROT6_AGE",1,
"ROT7_AGE",1,
"ROT8_AGE",1,
"ROT9_AGE",1,
"VRC1_AGE",2,
"VRC2_AGE",2,
"VRC3_AGE",2,
"VRC4_AGE",1,
"VRC5_AGE",1,
"VRC6_AGE",1,
"VRC7_AGE",1,
"VRC8_AGE",1,
"VRC9_AGE",1,
"XDTPTY1",2,
"XDTPTY2",2,
"XDTPTY3",2,
"XDTPTY4",2,
"XDTPTY5",2,
"XDTPTY6",2,
"XDTPTY7",2,
"XDTPTY8",1,
"XDTPTY9",1,
"XFLUTY1",2,
"XFLUTY2",2,
"XFLUTY3",2,
"XFLUTY4",2,
"XFLUTY5",2,
"XFLUTY6",2,
"XFLUTY7",2,
"XFLUTY8",1,
"XFLUTY9",1,
"XHEPTY1",2,
"XHEPTY2",2,
"XHEPTY3",2,
"XHEPTY4",2,
"XHEPTY5",2,
"XHEPTY6",2,
"XHEPTY7",2,
"XHEPTY8",1,
"XHEPTY9",1,
"XHIBTY1",2,
"XHIBTY2",2,
"XHIBTY3",2,
"XHIBTY4",2,
"XHIBTY5",2,
"XHIBTY6",2,
"XHIBTY7",2,
"XHIBTY8",1,
"XHIBTY9",1,
"XMMRTY1",2,
"XMMRTY2",2,
"XMMRTY3",2,
"XMMRTY4",1,
"XMMRTY5",1,
"XMMRTY6",1,
"XMMRTY7",1,
"XMMRTY8",1,
"XMMRTY9",1,
"XPCVTY1",2,
"XPCVTY2",2,
"XPCVTY3",2,
"XPCVTY4",2,
"XPCVTY5",2,
"XPCVTY6",2,
"XPCVTY7",2,
"XPCVTY8",1,
"XPCVTY9",1,
"XPOLTY1",2,
"XPOLTY2",2,
"XPOLTY3",2,
"XPOLTY4",2,
"XPOLTY5",2,
"XPOLTY6",2,
"XPOLTY7",2,
"XPOLTY8",1,
"XPOLTY9",1,
"XROTTY1",2,
"XROTTY2",2,
"XROTTY3",2,
"XROTTY4",2,
"XROTTY5",2,
"XROTTY6",1,
"XROTTY7",1,
"XROTTY8",1,
"XROTTY9",1,
"XVRCTY1",2,
"XVRCTY2",2,
"XVRCTY3",2,
"XVRCTY4",1,
"XVRCTY5",1,
"XVRCTY6",1,
"XVRCTY7",1,
"XVRCTY8",1,
"XVRCTY9",1,
"INS_STAT2_I",1,
"INS_BREAK_I",1
)

NAMEWIDTH <- matrix(LIST.NAMEWIDTH, length(LIST.NAMEWIDTH)/2, 2, byrow=T, dimnames = list(NULL, c("VARIABLE","WIDTH")))
NA_STRING <- c(" ", ".", " .", "  .", "   .", "   .    ", " .              ", "    .              ", "     .              ", "     .             ")

NISPUF20 <- read.fwf(flatfile, widths= as.numeric(NAMEWIDTH[,2]), col.names = NAMEWIDTH[,1], na.strings= NA_STRING, as.is=TRUE)

NISPUF20$SEQNUMC <- as.character(NISPUF20$SEQNUMC)
NISPUF20$SEQNUMHH <- as.character(NISPUF20$SEQNUMHH)
NISPUF20$XDTPTY1 <- as.character(NISPUF20$XDTPTY1)
NISPUF20$XDTPTY2 <- as.character(NISPUF20$XDTPTY2)
NISPUF20$XDTPTY3 <- as.character(NISPUF20$XDTPTY3)
NISPUF20$XDTPTY4 <- as.character(NISPUF20$XDTPTY4)
NISPUF20$XDTPTY5 <- as.character(NISPUF20$XDTPTY5)
NISPUF20$XDTPTY6 <- as.character(NISPUF20$XDTPTY6)
NISPUF20$XDTPTY7 <- as.character(NISPUF20$XDTPTY7)
NISPUF20$XDTPTY8 <- as.character(NISPUF20$XDTPTY8)
NISPUF20$XDTPTY9 <- as.character(NISPUF20$XDTPTY9)
NISPUF20$XFLUTY1 <- as.character(NISPUF20$XFLUTY1)
NISPUF20$XFLUTY2 <- as.character(NISPUF20$XFLUTY2)
NISPUF20$XFLUTY3 <- as.character(NISPUF20$XFLUTY3)
NISPUF20$XFLUTY4 <- as.character(NISPUF20$XFLUTY4)
NISPUF20$XFLUTY5 <- as.character(NISPUF20$XFLUTY5)
NISPUF20$XFLUTY6 <- as.character(NISPUF20$XFLUTY6)
NISPUF20$XFLUTY7 <- as.character(NISPUF20$XFLUTY7)
NISPUF20$XFLUTY8 <- as.character(NISPUF20$XFLUTY8)
NISPUF20$XFLUTY9 <- as.character(NISPUF20$XFLUTY9)
NISPUF20$XHEPTY1 <- as.character(NISPUF20$XHEPTY1)
NISPUF20$XHEPTY2 <- as.character(NISPUF20$XHEPTY2)
NISPUF20$XHEPTY3 <- as.character(NISPUF20$XHEPTY3)
NISPUF20$XHEPTY4 <- as.character(NISPUF20$XHEPTY4)
NISPUF20$XHEPTY5 <- as.character(NISPUF20$XHEPTY5)
NISPUF20$XHEPTY6 <- as.character(NISPUF20$XHEPTY6)
NISPUF20$XHEPTY7 <- as.character(NISPUF20$XHEPTY7)
NISPUF20$XHEPTY8 <- as.character(NISPUF20$XHEPTY8)
NISPUF20$XHEPTY9 <- as.character(NISPUF20$XHEPTY9)
NISPUF20$XHIBTY1 <- as.character(NISPUF20$XHIBTY1)
NISPUF20$XHIBTY2 <- as.character(NISPUF20$XHIBTY2)
NISPUF20$XHIBTY3 <- as.character(NISPUF20$XHIBTY3)
NISPUF20$XHIBTY4 <- as.character(NISPUF20$XHIBTY4)
NISPUF20$XHIBTY5 <- as.character(NISPUF20$XHIBTY5)
NISPUF20$XHIBTY6 <- as.character(NISPUF20$XHIBTY6)
NISPUF20$XHIBTY7 <- as.character(NISPUF20$XHIBTY7)
NISPUF20$XHIBTY8 <- as.character(NISPUF20$XHIBTY8)
NISPUF20$XHIBTY9 <- as.character(NISPUF20$XHIBTY9)
NISPUF20$XMMRTY1 <- as.character(NISPUF20$XMMRTY1)
NISPUF20$XMMRTY2 <- as.character(NISPUF20$XMMRTY2)
NISPUF20$XMMRTY3 <- as.character(NISPUF20$XMMRTY3)
NISPUF20$XMMRTY4 <- as.character(NISPUF20$XMMRTY4)
NISPUF20$XMMRTY5 <- as.character(NISPUF20$XMMRTY5)
NISPUF20$XMMRTY6 <- as.character(NISPUF20$XMMRTY6)
NISPUF20$XMMRTY7 <- as.character(NISPUF20$XMMRTY7)
NISPUF20$XMMRTY8 <- as.character(NISPUF20$XMMRTY8)
NISPUF20$XMMRTY9 <- as.character(NISPUF20$XMMRTY9)
NISPUF20$XPCVTY1 <- as.character(NISPUF20$XPCVTY1)
NISPUF20$XPCVTY2 <- as.character(NISPUF20$XPCVTY2)
NISPUF20$XPCVTY3 <- as.character(NISPUF20$XPCVTY3)
NISPUF20$XPCVTY4 <- as.character(NISPUF20$XPCVTY4)
NISPUF20$XPCVTY5 <- as.character(NISPUF20$XPCVTY5)
NISPUF20$XPCVTY6 <- as.character(NISPUF20$XPCVTY6)
NISPUF20$XPCVTY7 <- as.character(NISPUF20$XPCVTY7)
NISPUF20$XPCVTY8 <- as.character(NISPUF20$XPCVTY8)
NISPUF20$XPCVTY9 <- as.character(NISPUF20$XPCVTY9)
NISPUF20$XPOLTY1 <- as.character(NISPUF20$XPOLTY1)
NISPUF20$XPOLTY2 <- as.character(NISPUF20$XPOLTY2)
NISPUF20$XPOLTY3 <- as.character(NISPUF20$XPOLTY3)
NISPUF20$XPOLTY4 <- as.character(NISPUF20$XPOLTY4)
NISPUF20$XPOLTY5 <- as.character(NISPUF20$XPOLTY5)
NISPUF20$XPOLTY6 <- as.character(NISPUF20$XPOLTY6)
NISPUF20$XPOLTY7 <- as.character(NISPUF20$XPOLTY7)
NISPUF20$XPOLTY8 <- as.character(NISPUF20$XPOLTY8)
NISPUF20$XPOLTY9 <- as.character(NISPUF20$XPOLTY9)
NISPUF20$XROTTY1 <- as.character(NISPUF20$XROTTY1)
NISPUF20$XROTTY2 <- as.character(NISPUF20$XROTTY2)
NISPUF20$XROTTY3 <- as.character(NISPUF20$XROTTY3)
NISPUF20$XROTTY4 <- as.character(NISPUF20$XROTTY4)
NISPUF20$XROTTY5 <- as.character(NISPUF20$XROTTY5)
NISPUF20$XROTTY6 <- as.character(NISPUF20$XROTTY6)
NISPUF20$XROTTY7 <- as.character(NISPUF20$XROTTY7)
NISPUF20$XROTTY8 <- as.character(NISPUF20$XROTTY8)
NISPUF20$XROTTY9 <- as.character(NISPUF20$XROTTY9)
NISPUF20$XVRCTY1 <- as.character(NISPUF20$XVRCTY1)
NISPUF20$XVRCTY2 <- as.character(NISPUF20$XVRCTY2)
NISPUF20$XVRCTY3 <- as.character(NISPUF20$XVRCTY3)
NISPUF20$XVRCTY4 <- as.character(NISPUF20$XVRCTY4)
NISPUF20$XVRCTY5 <- as.character(NISPUF20$XVRCTY5)
NISPUF20$XVRCTY6 <- as.character(NISPUF20$XVRCTY6)
NISPUF20$XVRCTY7 <- as.character(NISPUF20$XVRCTY7)
NISPUF20$XVRCTY8 <- as.character(NISPUF20$XVRCTY8)
NISPUF20$XVRCTY9 <- as.character(NISPUF20$XVRCTY9)

############################################################################
# Step 4:   ASSIGN VARIABLE LABELS                                         #
############################################################################

label(NISPUF20$SEQNUMC) <- "UNIQUE CHILD IDENTIFIER"
label(NISPUF20$SEQNUMHH) <- "UNIQUE HOUSEHOLD IDENTIFIER"
label(NISPUF20$PDAT) <- "CHILD HAS ADEQUATE PROVIDER DATA"
label(NISPUF20$PROVWT_C) <- "FINAL SINGLE-FRAME CELL-PHONE PROVIDER-PHASE WEIGHT (EXCLUDES TERRITORIES)"
label(NISPUF20$PROVWT_C_TERR) <- "FINAL SINGLE-FRAME CELL-PHONE PROVIDER-PHASE WEIGHT INCLUDING TERRITORIES"

label(NISPUF20$RDDWT_C) <- "FINAL SINGLE-FRAME CELL-PHONE RDD-PHASE WEIGHT (EXCLUDES TERRITORIES)"
label(NISPUF20$RDDWT_C_TERR) <- "FINAL SINGLE-FRAME CELL-PHONE RDD-PHASE WEIGHT INCLUDING TERRITORIES"
label(NISPUF20$STRATUM) <- "STRATUM VARIABLE FOR VARIANCE ESTIMATION"
label(NISPUF20$YEAR) <- "YEAR OF INTERVIEW"
label(NISPUF20$AGECPOXR) <- "AGE IN MONTHS AT CHICKEN POX DISEASE (RECODE)"

label(NISPUF20$HAD_CPOX) <- "CHILD EVER HAD CHICKEN POX DISEASE?"
label(NISPUF20$AGEGRP) <- "AGE CATEGORY OF CHILD (19-23, 24-29, 30-35 MO) (RECODE)"
label(NISPUF20$BF_ENDR06) <- "DURATION OF BREASTFEEDING IN DAYS (RECODE)"
label(NISPUF20$BF_EXCLR06) <- "DURATION OF EXCLUSIVE BREAST/FORMULA FEEDING IN DAYS (RECODE)"
label(NISPUF20$BF_FORMR20) <- "AGE IN DAYS WHEN CHILD FIRST FED FORMULA (RECODE)"

label(NISPUF20$BFENDFL06) <- "DURATION OF BREAST FEEDING EXCEEDS CHILD AGE IN DAYS, WITH BUFFER"
label(NISPUF20$BFFORMFL06) <- "AGE IN DAYS WHEN CHILD FIRST FED FORMULA EXCEEDS CHILD AGE IN DAYS, WITH BUFFER"
label(NISPUF20$C1R) <- "NUMBER OF PEOPLE IN HOUSEHOLD (RECODE)"
label(NISPUF20$C5R) <- "RELATIONSHIP OF RESPONDENT TO CHILD (RECODE)"
label(NISPUF20$CBF_01) <- "WAS CHILD EVER BREASTFED OR FED BREAST MILK?"

label(NISPUF20$CEN_REG) <- "CENSUS REGION BASED ON TRUE STATE OF RESIDENCE"
label(NISPUF20$CHILDNM) <- "NUMBER OF CHILDREN LESS THAN 18 YEARS IN HH (RECODE)"
label(NISPUF20$CWIC_01) <- "CHILD EVER RECEIVED WIC BENEFITS?"
label(NISPUF20$CWIC_02) <- "CHILD CURRENTLY RECEIVING WIC BENEFITS?"
label(NISPUF20$EDUC1) <- "EDUCATION OF MOTHER CATEGORIES: IMPUTED (RECODE)"

label(NISPUF20$FRSTBRN) <- "FIRST BORN STATUS OF CHILD: IMPUTED"
label(NISPUF20$I_HISP_K) <- "HISPANIC ORIGIN OF CHILD: IMPUTED"
label(NISPUF20$INCPORAR) <- "INCOME TO POVERTY RATIO (RECODE)"
label(NISPUF20$INCPORAR_I) <- "INCOME TO POVERTY RATIO: IMPUTED (RECODE)"
label(NISPUF20$INCPOV1) <- "POVERTY STATUS"

label(NISPUF20$INCQ298A) <- "FAMILY INCOME CATEGORIES (RECODE)"
label(NISPUF20$LANGUAGE) <- "LANGUAGE IN WHICH INTERVIEW WAS CONDUCTED"
label(NISPUF20$M_AGEGRP2) <- "AGE OF MOTHER CATEGORIES: IMPUTED (RECODE)"
label(NISPUF20$MARITAL2) <- "MARITAL STATUS OF MOTHER: IMPUTED (RECODE)"
label(NISPUF20$MOBIL_I) <- "GEOGRAPHIC MOBILITY STATUS: STATE OF RESIDENCE OF CHILD AT BIRTH VERSUS CURRENT STATE: IMPUTED"

label(NISPUF20$NUM_PHONE) <- "NUMBER OF RESIDENTIAL TELEPHONE NUMBERS IN HOUSEHOLD (EXCLUDING CELL PHONES)"
label(NISPUF20$NUM_CELLS_HH) <- "NUMBER OF WORKING CELL PHONES HOUSEHOLD MEMBERS HAVE AVAILABLE FOR PERSONAL USE"
label(NISPUF20$NUM_CELLS_PARENTS) <- "NUMBER OF WORKING CELL PHONES USUALLY USED BY PARENTS OR GUARDIANS"
label(NISPUF20$RACE_K) <- "RACE OF CHILD: IMPUTED (RECODE)"
label(NISPUF20$RACEETHK) <- "RACE/ETHNICITY OF CHILD: IMPUTED (RECODE)"

label(NISPUF20$RENT_OWN) <- "IS HOME OWNED/BEING BOUGHT, RENTED, OR OCCUPIED BY SOME OTHER ARRANGEMENT?"
label(NISPUF20$SEX) <- "SEX OF CHILD: IMPUTED"
label(NISPUF20$ESTIAP20) <- "ESTIMATION AREA OF RESIDENCE"
label(NISPUF20$EST_GRANT) <- "AREA OF RESIDENCE ACCORDING TO THE 56 ORIGINAL CORE GRANTEE AREAS"
label(NISPUF20$STATE) <- "TRUE STATE OF RESIDENCE (STATE FIPS CODE)"

label(NISPUF20$D6R) <- "NUMBER OF VACCINATION PROVIDERS IDENTIFIED BY RESPONDENT (RECODE)"
label(NISPUF20$D7) <- "CONSENT TO OBTAIN CHILD'S IMMUNIZATION RECORDS FROM PROVIDERS"
label(NISPUF20$N_PRVR) <- "NUMBER OF PROVIDERS RESPONDING WITH VACCINATION DATA FOR CHILD (RECODE)"
label(NISPUF20$PROV_FAC) <- "PROVIDER FACILITY TYPES: IMPUTED"
label(NISPUF20$REGISTRY) <- "CHILD'S PROVIDERS REPORTED CHILD'S VACCINATIONS TO IMMUNIZATION REGISTRY"

label(NISPUF20$VFC_ORDER) <- "DO CHILD'S PROVIDERS ORDER VACCINES FROM STATE/LOCAL HEALTH DEPT?"
label(NISPUF20$HEP_BRTH) <- "HEPATITIS B-CONTAINING SHOT GIVEN AT BIRTH FLAG"
label(NISPUF20$HEP_FLAG) <- "HEPATITIS B BIRTH SHOT DATE IMPUTATION FLAG"
label(NISPUF20$P_NUHEPX) <- "NUMBER OF HEPATITIS B-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUHIBX) <- "NUMBER OF HIB-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF20$P_NUHPHB) <- "NUMBER OF HEPATITIS B/HIB COMBO SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMDAH) <- "NUMBER OF DTAP/HIB COMBO SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMDHI) <- "NUMBER OF DTAP/HEPB/IPV COMBO SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMDIH) <- "NUMBER OF DTAP/IPV/HIB COMBO SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_NUMDTA) <- "NUMBER OF DTAP-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF20$P_NUMDTP) <- "NUMBER OF DT-CONTAINING SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMFLU) <- "NUMBER OF SEASONAL FLU-CONTAINING VACCINATIONS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMFLUL) <- "NUMBER OF SEASONAL FLU-CONTAINING VACCINATIONS OF UNKNOWN TYPE BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMFLUM) <- "NUMBER OF SEASONAL FLU SPRAY VACCINATIONS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMFLUN) <- "NUMBER OF INJECTED SEASONAL FLU VACCINATIONS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF20$P_NUMHEA) <- "NUMBER OF HEPATITIS A-CONTAINING SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMHEN) <- "NUMBER OF HEPATITIS B-CONTAINING SHOTS OF UNKNOWN TYPE BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMHEP) <- "NUMBER OF HEPATITIS B-CONTAINING SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMHG) <- "NUMBER OF HIB-GLAXOSMITHKLINE SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_NUMHHY) <- "NUMBER OF HIB-MENCY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."

label(NISPUF20$P_NUMHIB) <- "NUMBER OF HIB-CONTAINING SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMHIN) <- "NUMBER OF HIB-CONTAINING SHOTS OF UNKNOWN TYPE BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMHION) <- "NUMBER OF HIB-ONLY SHOTS OF UNKNOWN TYPE BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_NUMHM) <- "NUMBER OF HIB-MERCK SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_NUMHS) <- "NUMBER OF HIB-SANOFI SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."

label(NISPUF20$P_NUMIPV) <- "NUMBER OF IPV-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMMCN) <- "NUMBER OF MEASLES-CONTAINING SHOTS OF UNKNOWN TYPE BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMMMR) <- "NUMBER OF MEASLES-CONTAINING SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMMMRX) <- "NUMBER OF MMR-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMMMX) <- "NUMBER OF MMR-CONTAINING SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF20$P_NUMMP) <- "NUMBER OF MUMPS-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMMPR) <- "NUMBER OF (MUMPS/RUBELLA)-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMMRV) <- "NUMBER OF MMR/VARICELLA COMBO SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMMS) <- "NUMBER OF MEASLES-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMMSM) <- "NUMBER OF MEASLES/MUMPS COMBO SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF20$P_NUMMSR) <- "NUMBER OF MEASLES/RUBELLA COMBO SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMOLN) <- "NUMBER OF POLIO SHOTS OF UNKNOWN TYPE BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMOPV) <- "NUMBER OF OPV-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMPCV) <- "NUMBER OF PNEUMOCOCCAL-CONTAINING SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_NUMPCP) <- "NUMBER OF PNEUMOCOCCAL POLYSACCHARIDE SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."

label(NISPUF20$P_NUMPCC) <- "NUMBER OF PNEUMOCOCCAL CONJUGATE SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_NUMPCC7) <- "NUMBER OF PNEUMOCOCCAL CONJUGATE-7 SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_NUMPCC13) <- "NUMBER OF PNEUMOCOCCAL CONJUGATE-13 SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_NUMPCCN) <- "NUMBER OF PNEUMOCOCCAL CONJUGATE SHOTS OF UNKNOWN TYPE BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_NUMPCN) <- "NUMBER OF PNEUMOCOCCAL SHOTS OF UNKNOWN TYPE BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."

label(NISPUF20$P_NUMPOL) <- "NUMBER OF POLIO-CONTAINING SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMRB) <- "NUMBER OF RUBELLA-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMRG) <- "NUMBER OF ROTARIX-GSK SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_NUMRM) <- "NUMBER OF ROTATEQ-MERCK SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_NUMRO) <- "NUMBER OF ROTAVIRUS SHOTS OF UNKNOWN TYPE BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."

label(NISPUF20$P_NUMROT) <- "NUMBER OF ROTAVIRUS-CONTAINING SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMTPN) <- "NUMBER OF DT-CONTAINING SHOTS OF UNKNOWN TYPE BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMVRC) <- "NUMBER OF VARICELLA-CONTAINING SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMVRN) <- "NUMBER OF VARICELLA-CONTAINING SHOTS OF UNKNOWN TYPE BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF20$P_NUMVRX) <- "NUMBER OF VARICELLA-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF20$P_U12VRC) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 1+ VARICELLA-CONTAINING SHOT AT 12+ MONTHS OF AGE, BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_UTD331) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3:3:1 BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_UTD431) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1 BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_UTDHEP) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ HEPATITIS B-CONTAINING SHOTS BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_UTDHEPA1) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 1+ HEPATITIS A-CONTAINING SHOTS BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."

label(NISPUF20$P_UTDHEPA2) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 2+ HEPATITIS A-CONTAINING SHOTS BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_UTDHIB) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ HIB-CONTAINING SHOTS BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_UTDHIB_ROUT_S) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ HIB DOSES BY 36 MONTHS OF AGE, BASED ON THE ROUTINE (NON-SHORTAGE) HIB RECOMMENDATIONS AND A STRICT TREATMENT OF HIB SHOTS OF UNKNOWN TYPE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSE
HOLD INTERVIEW DATE."
label(NISPUF20$P_UTDHIB_SHORT_S) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ HIB DOSES BY 36 MONTHS OF AGE, BASED ON THE HIB SHORTAGE RECOMMENDATIONS AND A STRICT TREATMENT OF HIB SHOTS OF UNKNOWN TYPE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIE
W DATE."
label(NISPUF20$P_UTDMCV) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 1+ MEASLES-CONTAINING SHOT BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."

label(NISPUF20$P_UTDMMX) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 1+ MMR COMBO SHOT BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_UTDPC3) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ PNEUMOCOCCAL-CONTAINING SHOTS BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_UTDPCV) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4+ PNEUMOCOCCAL-CONTAINING SHOTS BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_UTDPCVB13) <- "UTD (UP-TO-DATE) INDICATOR FOR PROVIDER 1+ PNEUMOCOCCAL VACCINATIONS OF TYPE CONJUGATE-13, GIVEN 4+ DOSES OF TYPE CONJUGATE-7, BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_UTDPOL) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ POLIO-CONTAINING SHOTS BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."

label(NISPUF20$P_UTDROT_S) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ ROTAVIRUS DOSES BY 36 MONTHS OF AGE, BASED ON A STRICT TREATMENT OF ROTAVIRUS VACCINATIONS OF UNKNOWN TYPE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_UTDTP3) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ DT-CONTAINING SHOTS BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_UTDTP4) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4+ DT-CONTAINING SHOTS BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$PU431331) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1:3:3:1 (INCLUDES 1+ VARICELLA AT AGE 12+ MTHS) BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_UTD431H31_ROUT_S) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1:3:3:1 BY 36 MONTHS OF AGE (INCLUDES 1+ VARICELLA-CONTAINING AT AGE 12+ MTHS) USING THE ROUTINE, STRICT DEFINITION OF HIB UTD, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INT
ERVIEW DATE."

label(NISPUF20$PU4313313) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1:3:3:1:3 (INCLUDES 1+ VARICELLA AT AGE 12+ MTHS) BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_UTD431H313_ROUT_S) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1:3:3:1:3 BY 36 MONTHS OF AGE (INCLUDES 1+ VARICELLA-CONTAINING AT AGE 12+ MTHS) USING THE ROUTINE, STRICT DEFINITION OF HIB UTD, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD 
INTERVIEW DATE."
label(NISPUF20$PU4313314) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1:3:3:1:4 (INCLUDES 1+ VARICELLA AT AGE 12+ MTHS) BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_UTD431H314_ROUT_S) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1:3:3:1:4 BY 36 MONTHS OF AGE (INCLUDES 1+ VARICELLA-CONTAINING AT AGE 12+ MTHS) USING THE ROUTINE, STRICT DEFINITION OF HIB UTD, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD 
INTERVIEW DATE."
label(NISPUF20$PUT43133) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1:3:3 BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."

label(NISPUF20$P_UTD431H3_ROUT_S) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1:3:3 BY 36 MONTHS OF AGE, USING THE ROUTINE, STRICT DEFINITION OF HIB UTD, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$PUTD4313) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1:3 BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$P_UTD431H_ROUT_S) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1:3 BY 36 MONTHS OF AGE, USING THE ROUTINE, STRICT DEFINITION OF HIB UTD, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$U24_FLU_24D) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 2+ INFLUENZA VACCINATIONS AT LEAST 4 WEEKS-4 DAYS APART BY 24 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$U19_FLU_24D) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 2+ INFLUENZA VACCINATIONS AT LEAST 4 WEEKS-4 DAYS APART BY 19 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."

label(NISPUF20$U24_FLU3_24D) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ INFLUENZA VACCINATIONS AT LEAST 4 WEEKS-4 DAYS APART BY 24 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF20$U1D_HEP) <- "BIRTH DOSE HEPATITIS B-CONTAINING GIVEN FROM BIRTH TO DAY 1 FLAG"
label(NISPUF20$U2D_HEP) <- "BIRTH DOSE HEPATITIS B-CONTAINING GIVEN FROM BIRTH TO DAY 2 FLAG"
label(NISPUF20$U3D_HEP) <- "BIRTH DOSE HEPATITIS B-CONTAINING GIVEN FROM BIRTH TO DAY 3 FLAG"
label(NISPUF20$DDTP1) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #1"

label(NISPUF20$DDTP2) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #2"
label(NISPUF20$DDTP3) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #3"
label(NISPUF20$DDTP4) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #4"
label(NISPUF20$DDTP5) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #5"
label(NISPUF20$DDTP6) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #6"

label(NISPUF20$DDTP7) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #7"
label(NISPUF20$DDTP8) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #8"
label(NISPUF20$DDTP9) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #9"
label(NISPUF20$DFLU1) <- "AGE IN DAYS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #1"
label(NISPUF20$DFLU2) <- "AGE IN DAYS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #2"

label(NISPUF20$DFLU3) <- "AGE IN DAYS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #3"
label(NISPUF20$DFLU4) <- "AGE IN DAYS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #4"
label(NISPUF20$DFLU5) <- "AGE IN DAYS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #5"
label(NISPUF20$DFLU6) <- "AGE IN DAYS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #6"
label(NISPUF20$DFLU7) <- "AGE IN DAYS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #7"

label(NISPUF20$DFLU8) <- "AGE IN DAYS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #8"
label(NISPUF20$DFLU9) <- "AGE IN DAYS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #9"
label(NISPUF20$DHEPA1) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #1"
label(NISPUF20$DHEPA2) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #2"
label(NISPUF20$DHEPA3) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #3"

label(NISPUF20$DHEPA4) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #4"
label(NISPUF20$DHEPA5) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #5"
label(NISPUF20$DHEPA6) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #6"
label(NISPUF20$DHEPA7) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #7"
label(NISPUF20$DHEPA8) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #8"

label(NISPUF20$DHEPA9) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #9"
label(NISPUF20$DHEPB1) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #1"
label(NISPUF20$DHEPB2) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #2"
label(NISPUF20$DHEPB3) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #3"
label(NISPUF20$DHEPB4) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #4"

label(NISPUF20$DHEPB5) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #5"
label(NISPUF20$DHEPB6) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #6"
label(NISPUF20$DHEPB7) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #7"
label(NISPUF20$DHEPB8) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #8"
label(NISPUF20$DHEPB9) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #9"

label(NISPUF20$DHIB1) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #1"
label(NISPUF20$DHIB2) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #2"
label(NISPUF20$DHIB3) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #3"
label(NISPUF20$DHIB4) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #4"
label(NISPUF20$DHIB5) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #5"

label(NISPUF20$DHIB6) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #6"
label(NISPUF20$DHIB7) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #7"
label(NISPUF20$DHIB8) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #8"
label(NISPUF20$DHIB9) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #9"
label(NISPUF20$DMMR1) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #1"

label(NISPUF20$DMMR2) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #2"
label(NISPUF20$DMMR3) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #3"
label(NISPUF20$DMMR4) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #4"
label(NISPUF20$DMMR5) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #5"
label(NISPUF20$DMMR6) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #6"

label(NISPUF20$DMMR7) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #7"
label(NISPUF20$DMMR8) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #8"
label(NISPUF20$DMMR9) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #9"
label(NISPUF20$DMP1) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #1"
label(NISPUF20$DMP2) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #2"

label(NISPUF20$DMP3) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #3"
label(NISPUF20$DMP4) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #4"
label(NISPUF20$DMP5) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #5"
label(NISPUF20$DMP6) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #6"
label(NISPUF20$DMP7) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #7"

label(NISPUF20$DMP8) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #8"
label(NISPUF20$DMP9) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #9"
label(NISPUF20$DMPRB1) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #1"
label(NISPUF20$DMPRB2) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #2"
label(NISPUF20$DMPRB3) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #3"

label(NISPUF20$DMPRB4) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #4"
label(NISPUF20$DMPRB5) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #5"
label(NISPUF20$DMPRB6) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #6"
label(NISPUF20$DMPRB7) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #7"
label(NISPUF20$DMPRB8) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #8"

label(NISPUF20$DMPRB9) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #9"
label(NISPUF20$DPCV1) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #1"
label(NISPUF20$DPCV2) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #2"
label(NISPUF20$DPCV3) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #3"
label(NISPUF20$DPCV4) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #4"

label(NISPUF20$DPCV5) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #5"
label(NISPUF20$DPCV6) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #6"
label(NISPUF20$DPCV7) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #7"
label(NISPUF20$DPCV8) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #8"
label(NISPUF20$DPCV9) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #9"

label(NISPUF20$DPOLIO1) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #1"
label(NISPUF20$DPOLIO2) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #2"
label(NISPUF20$DPOLIO3) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #3"
label(NISPUF20$DPOLIO4) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #4"
label(NISPUF20$DPOLIO5) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #5"

label(NISPUF20$DPOLIO6) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #6"
label(NISPUF20$DPOLIO7) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #7"
label(NISPUF20$DPOLIO8) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #8"
label(NISPUF20$DPOLIO9) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #9"
label(NISPUF20$DRB1) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #1"

label(NISPUF20$DRB2) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #2"
label(NISPUF20$DRB3) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #3"
label(NISPUF20$DRB4) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #4"
label(NISPUF20$DRB5) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #5"
label(NISPUF20$DRB6) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #6"

label(NISPUF20$DRB7) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #7"
label(NISPUF20$DRB8) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #8"
label(NISPUF20$DRB9) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #9"
label(NISPUF20$DROT1) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #1"
label(NISPUF20$DROT2) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #2"

label(NISPUF20$DROT3) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #3"
label(NISPUF20$DROT4) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #4"
label(NISPUF20$DROT5) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #5"
label(NISPUF20$DROT6) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #6"
label(NISPUF20$DROT7) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #7"

label(NISPUF20$DROT8) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #8"
label(NISPUF20$DROT9) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #9"
label(NISPUF20$DVRC1) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #1"
label(NISPUF20$DVRC2) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #2"
label(NISPUF20$DVRC3) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #3"

label(NISPUF20$DVRC4) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #4"
label(NISPUF20$DVRC5) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #5"
label(NISPUF20$DVRC6) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #6"
label(NISPUF20$DVRC7) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #7"
label(NISPUF20$DVRC8) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #8"

label(NISPUF20$DVRC9) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #9"
label(NISPUF20$DTP1_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #1"
label(NISPUF20$DTP2_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #2"
label(NISPUF20$DTP3_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #3"
label(NISPUF20$DTP4_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #4"

label(NISPUF20$DTP5_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #5"
label(NISPUF20$DTP6_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #6"
label(NISPUF20$DTP7_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #7"
label(NISPUF20$DTP8_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #8"
label(NISPUF20$DTP9_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #9"

label(NISPUF20$FLU1_AGE) <- "AGE IN MONTHS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #1"
label(NISPUF20$FLU2_AGE) <- "AGE IN MONTHS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #2"
label(NISPUF20$FLU3_AGE) <- "AGE IN MONTHS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #3"
label(NISPUF20$FLU4_AGE) <- "AGE IN MONTHS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #4"
label(NISPUF20$FLU5_AGE) <- "AGE IN MONTHS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #5"

label(NISPUF20$FLU6_AGE) <- "AGE IN MONTHS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #6"
label(NISPUF20$FLU7_AGE) <- "AGE IN MONTHS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #7"
label(NISPUF20$FLU8_AGE) <- "AGE IN MONTHS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #8"
label(NISPUF20$FLU9_AGE) <- "AGE IN MONTHS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #9"
label(NISPUF20$HEA1_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #1"

label(NISPUF20$HEA2_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #2"
label(NISPUF20$HEA3_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #3"
label(NISPUF20$HEA4_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #4"
label(NISPUF20$HEA5_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #5"
label(NISPUF20$HEA6_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #6"

label(NISPUF20$HEA7_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #7"
label(NISPUF20$HEA8_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #8"
label(NISPUF20$HEA9_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #9"
label(NISPUF20$HEP1_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #1"
label(NISPUF20$HEP2_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #2"

label(NISPUF20$HEP3_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #3"
label(NISPUF20$HEP4_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #4"
label(NISPUF20$HEP5_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #5"
label(NISPUF20$HEP6_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #6"
label(NISPUF20$HEP7_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #7"

label(NISPUF20$HEP8_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #8"
label(NISPUF20$HEP9_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #9"
label(NISPUF20$HIB1_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #1"
label(NISPUF20$HIB2_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #2"
label(NISPUF20$HIB3_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #3"

label(NISPUF20$HIB4_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #4"
label(NISPUF20$HIB5_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #5"
label(NISPUF20$HIB6_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #6"
label(NISPUF20$HIB7_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #7"
label(NISPUF20$HIB8_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #8"

label(NISPUF20$HIB9_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #9"
label(NISPUF20$MMR1_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #1"
label(NISPUF20$MMR2_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #2"
label(NISPUF20$MMR3_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #3"
label(NISPUF20$MMR4_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #4"

label(NISPUF20$MMR5_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #5"
label(NISPUF20$MMR6_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #6"
label(NISPUF20$MMR7_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #7"
label(NISPUF20$MMR8_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #8"
label(NISPUF20$MMR9_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #9"

label(NISPUF20$MP1_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #1"
label(NISPUF20$MP2_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #2"
label(NISPUF20$MP3_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #3"
label(NISPUF20$MP4_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #4"
label(NISPUF20$MP5_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #5"

label(NISPUF20$MP6_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #6"
label(NISPUF20$MP7_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #7"
label(NISPUF20$MP8_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #8"
label(NISPUF20$MP9_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #9"
label(NISPUF20$MPR1_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #1"

label(NISPUF20$MPR2_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #2"
label(NISPUF20$MPR3_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #3"
label(NISPUF20$MPR4_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #4"
label(NISPUF20$MPR5_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #5"
label(NISPUF20$MPR6_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #6"

label(NISPUF20$MPR7_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #7"
label(NISPUF20$MPR8_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #8"
label(NISPUF20$MPR9_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #9"
label(NISPUF20$PCV1_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #1"
label(NISPUF20$PCV2_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #2"

label(NISPUF20$PCV3_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #3"
label(NISPUF20$PCV4_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #4"
label(NISPUF20$PCV5_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #5"
label(NISPUF20$PCV6_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #6"
label(NISPUF20$PCV7_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #7"

label(NISPUF20$PCV8_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #8"
label(NISPUF20$PCV9_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #9"
label(NISPUF20$POL1_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #1"
label(NISPUF20$POL2_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #2"
label(NISPUF20$POL3_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #3"

label(NISPUF20$POL4_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #4"
label(NISPUF20$POL5_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #5"
label(NISPUF20$POL6_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #6"
label(NISPUF20$POL7_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #7"
label(NISPUF20$POL8_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #8"

label(NISPUF20$POL9_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #9"
label(NISPUF20$RB1_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #1"
label(NISPUF20$RB2_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #2"
label(NISPUF20$RB3_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #3"
label(NISPUF20$RB4_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #4"

label(NISPUF20$RB5_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #5"
label(NISPUF20$RB6_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #6"
label(NISPUF20$RB7_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #7"
label(NISPUF20$RB8_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #8"
label(NISPUF20$RB9_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #9"

label(NISPUF20$ROT1_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #1"
label(NISPUF20$ROT2_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #2"
label(NISPUF20$ROT3_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #3"
label(NISPUF20$ROT4_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #4"
label(NISPUF20$ROT5_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #5"

label(NISPUF20$ROT6_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #6"
label(NISPUF20$ROT7_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #7"
label(NISPUF20$ROT8_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #8"
label(NISPUF20$ROT9_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #9"
label(NISPUF20$VRC1_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #1"

label(NISPUF20$VRC2_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #2"
label(NISPUF20$VRC3_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #3"
label(NISPUF20$VRC4_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #4"
label(NISPUF20$VRC5_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #5"
label(NISPUF20$VRC6_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #6"

label(NISPUF20$VRC7_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #7"
label(NISPUF20$VRC8_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #8"
label(NISPUF20$VRC9_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #9"
label(NISPUF20$XDTPTY1) <- "DT-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF20$XDTPTY2) <- "DT-CONTAINING VACCINATION #2 TYPE CODE"

label(NISPUF20$XDTPTY3) <- "DT-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF20$XDTPTY4) <- "DT-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF20$XDTPTY5) <- "DT-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF20$XDTPTY6) <- "DT-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF20$XDTPTY7) <- "DT-CONTAINING VACCINATION #7 TYPE CODE"

label(NISPUF20$XDTPTY8) <- "DT-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF20$XDTPTY9) <- "DT-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF20$XFLUTY1) <- "SEASONAL FLU-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF20$XFLUTY2) <- "SEASONAL FLU-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF20$XFLUTY3) <- "SEASONAL FLU-CONTAINING VACCINATION #3 TYPE CODE"

label(NISPUF20$XFLUTY4) <- "SEASONAL FLU-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF20$XFLUTY5) <- "SEASONAL FLU-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF20$XFLUTY6) <- "SEASONAL FLU-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF20$XFLUTY7) <- "SEASONAL FLU-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF20$XFLUTY8) <- "SEASONAL FLU-CONTAINING VACCINATION #8 TYPE CODE"

label(NISPUF20$XFLUTY9) <- "SEASONAL FLU-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF20$XHEPTY1) <- "HEPATITIS B-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF20$XHEPTY2) <- "HEPATITIS B-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF20$XHEPTY3) <- "HEPATITIS B-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF20$XHEPTY4) <- "HEPATITIS B-CONTAINING VACCINATION #4 TYPE CODE"

label(NISPUF20$XHEPTY5) <- "HEPATITIS B-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF20$XHEPTY6) <- "HEPATITIS B-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF20$XHEPTY7) <- "HEPATITIS B-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF20$XHEPTY8) <- "HEPATITIS B-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF20$XHEPTY9) <- "HEPATITIS B-CONTAINING VACCINATION #9 TYPE CODE"

label(NISPUF20$XHIBTY1) <- "HIB-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF20$XHIBTY2) <- "HIB-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF20$XHIBTY3) <- "HIB-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF20$XHIBTY4) <- "HIB-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF20$XHIBTY5) <- "HIB-CONTAINING VACCINATION #5 TYPE CODE"

label(NISPUF20$XHIBTY6) <- "HIB-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF20$XHIBTY7) <- "HIB-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF20$XHIBTY8) <- "HIB-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF20$XHIBTY9) <- "HIB-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF20$XMMRTY1) <- "MEASLES-CONTAINING VACCINATION #1 TYPE CODE"

label(NISPUF20$XMMRTY2) <- "MEASLES-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF20$XMMRTY3) <- "MEASLES-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF20$XMMRTY4) <- "MEASLES-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF20$XMMRTY5) <- "MEASLES-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF20$XMMRTY6) <- "MEASLES-CONTAINING VACCINATION #6 TYPE CODE"

label(NISPUF20$XMMRTY7) <- "MEASLES-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF20$XMMRTY8) <- "MEASLES-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF20$XMMRTY9) <- "MEASLES-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF20$XPCVTY1) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF20$XPCVTY2) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #2 TYPE CODE"

label(NISPUF20$XPCVTY3) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF20$XPCVTY4) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF20$XPCVTY5) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF20$XPCVTY6) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF20$XPCVTY7) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #7 TYPE CODE"

label(NISPUF20$XPCVTY8) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF20$XPCVTY9) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF20$XPOLTY1) <- "POLIO-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF20$XPOLTY2) <- "POLIO-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF20$XPOLTY3) <- "POLIO-CONTAINING VACCINATION #3 TYPE CODE"

label(NISPUF20$XPOLTY4) <- "POLIO-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF20$XPOLTY5) <- "POLIO-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF20$XPOLTY6) <- "POLIO-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF20$XPOLTY7) <- "POLIO-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF20$XPOLTY8) <- "POLIO-CONTAINING VACCINATION #8 TYPE CODE"

label(NISPUF20$XPOLTY9) <- "POLIO-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF20$XROTTY1) <- "ROTAVIRUS-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF20$XROTTY2) <- "ROTAVIRUS-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF20$XROTTY3) <- "ROTAVIRUS-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF20$XROTTY4) <- "ROTAVIRUS-CONTAINING VACCINATION #4 TYPE CODE"

label(NISPUF20$XROTTY5) <- "ROTAVIRUS-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF20$XROTTY6) <- "ROTAVIRUS-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF20$XROTTY7) <- "ROTAVIRUS-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF20$XROTTY8) <- "ROTAVIRUS-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF20$XROTTY9) <- "ROTAVIRUS-CONTAINING VACCINATION #9 TYPE CODE"

label(NISPUF20$XVRCTY1) <- "VARICELLA-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF20$XVRCTY2) <- "VARICELLA-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF20$XVRCTY3) <- "VARICELLA-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF20$XVRCTY4) <- "VARICELLA-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF20$XVRCTY5) <- "VARICELLA-CONTAINING VACCINATION #5 TYPE CODE"

label(NISPUF20$XVRCTY6) <- "VARICELLA-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF20$XVRCTY7) <- "VARICELLA-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF20$XVRCTY8) <- "VARICELLA-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF20$XVRCTY9) <- "VARICELLA-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF20$INS_STAT2_I) <- "INSURANCE STATUS (PRIVATE ONLY/ANY MEDICAID/OTHER INSURANCE/UNINSURED): IMPUTED"

label(NISPUF20$INS_BREAK_I) <- "CONTINUITY OF INSURANCE COVERAGE SINCE BIRTH: IMPUTED"

############################################################################
# Step 5:   CREATE A PERMANENT R DATASET                                   #
############################################################################

save(NISPUF20, file=paste(PUF, "/NISPUF20.RData", sep=""))

############################################################################
# Step 6:   ASSIGN FORMATS                                                 #
#	  FORMATS ARE APPLICABLE ONLY TO CATEGORICAL VARIABLES	IN R           #
############################################################################

NISPUF20$AGEGRP <- factor(NISPUF20$AGEGRP, levels=AGEGRPlevels, labels=AGEGRPlabels)
NISPUF20$LANGUAGE <- factor(NISPUF20$LANGUAGE, levels=LANGUAGElevels, labels=LANGUAGElabels)
NISPUF20$HAD_CPOX <- factor(NISPUF20$HAD_CPOX, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF20$CWIC_02 <- factor(NISPUF20$CWIC_02, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF20$CBF_01 <- factor(NISPUF20$CBF_01, levels=YNDKRFlevels, labels=YNDKRFlabels)

NISPUF20$D7 <- factor(NISPUF20$D7, levels=YNlevels, labels=YNlabels)
NISPUF20$BFENDFL06 <- factor(NISPUF20$BFENDFL06, levels=Ylevels, labels=Ylabels)
NISPUF20$BFFORMFL06 <- factor(NISPUF20$BFFORMFL06, levels=Ylevels, labels=Ylabels)
NISPUF20$CHILDNM <- factor(NISPUF20$CHILDNM, levels=CHILDNMlevels, labels=CHILDNMlabels)
NISPUF20$CWIC_01 <- factor(NISPUF20$CWIC_01, levels=CWIClevels, labels=CWIClabels)

NISPUF20$EDUC1 <- factor(NISPUF20$EDUC1, levels=EDUC1_levels, labels=EDUC1_labels)
NISPUF20$I_HISP_K <- factor(NISPUF20$I_HISP_K, levels=HISPlevels, labels=HISPlabels)
NISPUF20$MOBIL_I <- factor(NISPUF20$MOBIL_I, levels=MOBILlevels, labels=MOBILlabels)
NISPUF20$SEX <- factor(NISPUF20$SEX, levels=SEXlevels, labels=SEXlabels)
NISPUF20$INCPOV1 <- factor(NISPUF20$INCPOV1, levels=INCPOVlevels, labels=INCPOVlabels)

NISPUF20$PDAT <- factor(NISPUF20$PDAT, levels=HASPDA2Flevels, labels=HASPDA2Flabels)
NISPUF20$PROV_FAC <- factor(NISPUF20$PROV_FAC, levels=PROVIDlevels, labels=PROVIDlabels)
NISPUF20$REGISTRY <- factor(NISPUF20$REGISTRY, levels=REGISTRYlevels, labels=REGISTRYlabels)
NISPUF20$VFC_ORDER <- factor(NISPUF20$VFC_ORDER, levels=REGISTRYlevels, labels=REGISTRYlabels)
NISPUF20$XDTPTY1 <- factor(NISPUF20$XDTPTY1, levels=TYPElevels, labels=TYPElabels)

NISPUF20$XVRCTY9 <- factor(NISPUF20$XVRCTY9, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XVRCTY8 <- factor(NISPUF20$XVRCTY8, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XVRCTY7 <- factor(NISPUF20$XVRCTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XVRCTY6 <- factor(NISPUF20$XVRCTY6, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XVRCTY5 <- factor(NISPUF20$XVRCTY5, levels=TYPElevels, labels=TYPElabels)

NISPUF20$XVRCTY4 <- factor(NISPUF20$XVRCTY4, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XVRCTY3 <- factor(NISPUF20$XVRCTY3, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XVRCTY2 <- factor(NISPUF20$XVRCTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XVRCTY1 <- factor(NISPUF20$XVRCTY1, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XROTTY9 <- factor(NISPUF20$XROTTY9, levels=TYPElevels, labels=TYPElabels)

NISPUF20$XROTTY8 <- factor(NISPUF20$XROTTY8, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XROTTY7 <- factor(NISPUF20$XROTTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XROTTY6 <- factor(NISPUF20$XROTTY6, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XROTTY5 <- factor(NISPUF20$XROTTY5, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XROTTY4 <- factor(NISPUF20$XROTTY4, levels=TYPElevels, labels=TYPElabels)

NISPUF20$XROTTY3 <- factor(NISPUF20$XROTTY3, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XROTTY2 <- factor(NISPUF20$XROTTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XROTTY1 <- factor(NISPUF20$XROTTY1, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XPOLTY9 <- factor(NISPUF20$XPOLTY9, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XPOLTY8 <- factor(NISPUF20$XPOLTY8, levels=TYPElevels, labels=TYPElabels)

NISPUF20$XPOLTY7 <- factor(NISPUF20$XPOLTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XPOLTY6 <- factor(NISPUF20$XPOLTY6, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XPOLTY5 <- factor(NISPUF20$XPOLTY5, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XPOLTY4 <- factor(NISPUF20$XPOLTY4, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XPOLTY3 <- factor(NISPUF20$XPOLTY3, levels=TYPElevels, labels=TYPElabels)

NISPUF20$XPOLTY2 <- factor(NISPUF20$XPOLTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XPOLTY1 <- factor(NISPUF20$XPOLTY1, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XPCVTY9 <- factor(NISPUF20$XPCVTY9, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XPCVTY8 <- factor(NISPUF20$XPCVTY8, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XPCVTY7 <- factor(NISPUF20$XPCVTY7, levels=TYPElevels, labels=TYPElabels)

NISPUF20$XPCVTY6 <- factor(NISPUF20$XPCVTY6, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XPCVTY5 <- factor(NISPUF20$XPCVTY5, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XPCVTY4 <- factor(NISPUF20$XPCVTY4, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XPCVTY3 <- factor(NISPUF20$XPCVTY3, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XPCVTY2 <- factor(NISPUF20$XPCVTY2, levels=TYPElevels, labels=TYPElabels)

NISPUF20$XPCVTY1 <- factor(NISPUF20$XPCVTY1, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XMMRTY9 <- factor(NISPUF20$XMMRTY9, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XMMRTY8 <- factor(NISPUF20$XMMRTY8, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XMMRTY7 <- factor(NISPUF20$XMMRTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XMMRTY6 <- factor(NISPUF20$XMMRTY6, levels=TYPElevels, labels=TYPElabels)

NISPUF20$XMMRTY5 <- factor(NISPUF20$XMMRTY5, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XMMRTY4 <- factor(NISPUF20$XMMRTY4, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XMMRTY3 <- factor(NISPUF20$XMMRTY3, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XMMRTY2 <- factor(NISPUF20$XMMRTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XMMRTY1 <- factor(NISPUF20$XMMRTY1, levels=TYPElevels, labels=TYPElabels)

NISPUF20$XHIBTY9 <- factor(NISPUF20$XHIBTY9, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XHIBTY8 <- factor(NISPUF20$XHIBTY8, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XHIBTY7 <- factor(NISPUF20$XHIBTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XHIBTY6 <- factor(NISPUF20$XHIBTY6, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XHIBTY5 <- factor(NISPUF20$XHIBTY5, levels=TYPElevels, labels=TYPElabels)

NISPUF20$XHIBTY4 <- factor(NISPUF20$XHIBTY4, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XHIBTY3 <- factor(NISPUF20$XHIBTY3, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XHIBTY2 <- factor(NISPUF20$XHIBTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XHIBTY1 <- factor(NISPUF20$XHIBTY1, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XHEPTY9 <- factor(NISPUF20$XHEPTY9, levels=TYPElevels, labels=TYPElabels)

NISPUF20$XHEPTY8 <- factor(NISPUF20$XHEPTY8, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XHEPTY7 <- factor(NISPUF20$XHEPTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XHEPTY6 <- factor(NISPUF20$XHEPTY6, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XHEPTY5 <- factor(NISPUF20$XHEPTY5, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XHEPTY4 <- factor(NISPUF20$XHEPTY4, levels=TYPElevels, labels=TYPElabels)

NISPUF20$XHEPTY3 <- factor(NISPUF20$XHEPTY3, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XHEPTY2 <- factor(NISPUF20$XHEPTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XHEPTY1 <- factor(NISPUF20$XHEPTY1, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XFLUTY9 <- factor(NISPUF20$XFLUTY9, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XFLUTY8 <- factor(NISPUF20$XFLUTY8, levels=TYPElevels, labels=TYPElabels)

NISPUF20$XFLUTY7 <- factor(NISPUF20$XFLUTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XFLUTY6 <- factor(NISPUF20$XFLUTY6, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XFLUTY5 <- factor(NISPUF20$XFLUTY5, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XFLUTY4 <- factor(NISPUF20$XFLUTY4, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XFLUTY3 <- factor(NISPUF20$XFLUTY3, levels=TYPElevels, labels=TYPElabels)

NISPUF20$XFLUTY2 <- factor(NISPUF20$XFLUTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XFLUTY1 <- factor(NISPUF20$XFLUTY1, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XDTPTY9 <- factor(NISPUF20$XDTPTY9, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XDTPTY8 <- factor(NISPUF20$XDTPTY8, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XDTPTY7 <- factor(NISPUF20$XDTPTY7, levels=TYPElevels, labels=TYPElabels)

NISPUF20$XDTPTY6 <- factor(NISPUF20$XDTPTY6, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XDTPTY5 <- factor(NISPUF20$XDTPTY5, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XDTPTY4 <- factor(NISPUF20$XDTPTY4, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XDTPTY3 <- factor(NISPUF20$XDTPTY3, levels=TYPElevels, labels=TYPElabels)
NISPUF20$XDTPTY2 <- factor(NISPUF20$XDTPTY2, levels=TYPElevels, labels=TYPElabels)

NISPUF20$HEP_BRTH <- factor(NISPUF20$HEP_BRTH, levels=HEPBRTlevels, labels=HEPBRTlabels)
NISPUF20$HEP_FLAG <- factor(NISPUF20$HEP_FLAG, levels=HEPFLGlevels, labels=HEPFLGlabels)
NISPUF20$P_U12VRC <- factor(NISPUF20$P_U12VRC, levels=UTDlevels, labels=UTDlabels)
NISPUF20$U3D_HEP <- factor(NISPUF20$U3D_HEP, levels=UTDlevels, labels=UTDlabels)
NISPUF20$U2D_HEP <- factor(NISPUF20$U2D_HEP, levels=UTDlevels, labels=UTDlabels)

NISPUF20$U1D_HEP <- factor(NISPUF20$U1D_HEP, levels=UTDlevels, labels=UTDlabels)
NISPUF20$U24_FLU3_24D <- factor(NISPUF20$U24_FLU3_24D, levels=UTDlevels, labels=UTDlabels)
NISPUF20$U19_FLU_24D <- factor(NISPUF20$U19_FLU_24D, levels=UTDlevels, labels=UTDlabels)
NISPUF20$U24_FLU_24D <- factor(NISPUF20$U24_FLU_24D, levels=UTDlevels, labels=UTDlabels)
NISPUF20$P_UTD431H_ROUT_S <- factor(NISPUF20$P_UTD431H_ROUT_S, levels=UTDlevels, labels=UTDlabels)

NISPUF20$PUTD4313 <- factor(NISPUF20$PUTD4313, levels=UTDlevels, labels=UTDlabels)
NISPUF20$P_UTD431H3_ROUT_S <- factor(NISPUF20$P_UTD431H3_ROUT_S, levels=UTDlevels, labels=UTDlabels)
NISPUF20$PUT43133 <- factor(NISPUF20$PUT43133, levels=UTDlevels, labels=UTDlabels)
NISPUF20$P_UTD431H314_ROUT_S <- factor(NISPUF20$P_UTD431H314_ROUT_S, levels=UTDlevels, labels=UTDlabels)
NISPUF20$PU4313314 <- factor(NISPUF20$PU4313314, levels=UTDlevels, labels=UTDlabels)

NISPUF20$P_UTD431H313_ROUT_S <- factor(NISPUF20$P_UTD431H313_ROUT_S, levels=UTDlevels, labels=UTDlabels)
NISPUF20$PU4313313 <- factor(NISPUF20$PU4313313, levels=UTDlevels, labels=UTDlabels)
NISPUF20$P_UTD431H31_ROUT_S <- factor(NISPUF20$P_UTD431H31_ROUT_S, levels=UTDlevels, labels=UTDlabels)
NISPUF20$PU431331 <- factor(NISPUF20$PU431331, levels=UTDlevels, labels=UTDlabels)
NISPUF20$P_UTDTP4 <- factor(NISPUF20$P_UTDTP4, levels=UTDlevels, labels=UTDlabels)

NISPUF20$P_UTDTP3 <- factor(NISPUF20$P_UTDTP3, levels=UTDlevels, labels=UTDlabels)
NISPUF20$P_UTDROT_S <- factor(NISPUF20$P_UTDROT_S, levels=UTDlevels, labels=UTDlabels)
NISPUF20$P_UTDPOL <- factor(NISPUF20$P_UTDPOL, levels=UTDlevels, labels=UTDlabels)
NISPUF20$P_UTDPCV <- factor(NISPUF20$P_UTDPCV, levels=UTDlevels, labels=UTDlabels)
NISPUF20$P_UTDPC3 <- factor(NISPUF20$P_UTDPC3, levels=UTDlevels, labels=UTDlabels)

NISPUF20$P_UTDMMX <- factor(NISPUF20$P_UTDMMX, levels=UTDlevels, labels=UTDlabels)
NISPUF20$P_UTDMCV <- factor(NISPUF20$P_UTDMCV, levels=UTDlevels, labels=UTDlabels)
NISPUF20$P_UTDHIB_SHORT_S <- factor(NISPUF20$P_UTDHIB_SHORT_S, levels=UTDlevels, labels=UTDlabels)
NISPUF20$P_UTDHIB_ROUT_S <- factor(NISPUF20$P_UTDHIB_ROUT_S, levels=UTDlevels, labels=UTDlabels)
NISPUF20$P_UTDHIB <- factor(NISPUF20$P_UTDHIB, levels=UTDlevels, labels=UTDlabels)

NISPUF20$P_UTDHEPA2 <- factor(NISPUF20$P_UTDHEPA2, levels=UTDlevels, labels=UTDlabels)
NISPUF20$P_UTDHEPA1 <- factor(NISPUF20$P_UTDHEPA1, levels=UTDlevels, labels=UTDlabels)
NISPUF20$P_UTDHEP <- factor(NISPUF20$P_UTDHEP, levels=UTDlevels, labels=UTDlabels)
NISPUF20$P_UTD431 <- factor(NISPUF20$P_UTD431, levels=UTDlevels, labels=UTDlabels)
NISPUF20$P_UTD331 <- factor(NISPUF20$P_UTD331, levels=UTDlevels, labels=UTDlabels)

NISPUF20$CEN_REG <- factor(NISPUF20$CEN_REG, levels=CENREGlevels, labels=CENREGlabels)
NISPUF20$STATE <- factor(NISPUF20$STATE, levels=STATElevels, labels=STATElabels)
NISPUF20$RACE_K <- factor(NISPUF20$RACE_K, levels=RACE_PUFlevels, labels=RACE_PUFlabels)
NISPUF20$AGECPOXR <- factor(NISPUF20$AGECPOXR, levels=AGECPOXRlevels, labels=AGECPOXRlabels)
NISPUF20$C1R <- factor(NISPUF20$C1R, levels=C1Rlevels, labels=C1Rlabels)

NISPUF20$C5R <- factor(NISPUF20$C5R, levels=C5Rlevels, labels=C5Rlabels)
NISPUF20$INCQ298A <- factor(NISPUF20$INCQ298A, levels=INCQ298Alevels, labels=INCQ298Alabels)
NISPUF20$RACEETHK <- factor(NISPUF20$RACEETHK, levels=RACEETHKlevels, labels=RACEETHKlabels)
NISPUF20$D6R <- factor(NISPUF20$D6R, levels=D6Rlevels, labels=D6Rlabels)
NISPUF20$N_PRVR <- factor(NISPUF20$N_PRVR, levels=D6Rlevels, labels=D6Rlabels)

NISPUF20$FRSTBRN <- factor(NISPUF20$FRSTBRN, levels=FRSTBRNlevels, labels=FRSTBRNlabels)
NISPUF20$RENT_OWN <- factor(NISPUF20$RENT_OWN, levels=RENTOWNlevels, labels=RENTOWNlabels)
NISPUF20$NUM_PHONE <- factor(NISPUF20$NUM_PHONE, levels=NUM_PHONlevels, labels=NUM_PHONlabels)
NISPUF20$NUM_CELLS_PARENTS <- factor(NISPUF20$NUM_CELLS_PARENTS, levels=NUM_PHONlevels, labels=NUM_PHONlabels)
NISPUF20$NUM_CELLS_HH <- factor(NISPUF20$NUM_CELLS_HH, levels=NUM_PHONlevels, labels=NUM_PHONlabels)

NISPUF20$MARITAL2 <- factor(NISPUF20$MARITAL2, levels=MAR_PUF2_levels, labels=MAR_PUF2_labels)
NISPUF20$P_UTDPCVB13 <- factor(NISPUF20$P_UTDPCVB13, levels=UTDPCVBlevels, labels=UTDPCVBlabels)
NISPUF20$EST_GRANT <- factor(NISPUF20$EST_GRANT, levels=ESTGRANTlevels, labels=ESTGRANTlabels)
NISPUF20$INS_BREAK_I <- factor(NISPUF20$INS_BREAK_I, levels=INS_BREAK_Ilevels, labels=INS_BREAK_Ilabels)
NISPUF20$M_AGEGRP2 <- factor(NISPUF20$M_AGEGRP2, levels=MAGEGRP2_levels, labels=MAGEGRP2_labels)

NISPUF20$INS_STAT2_I <- factor(NISPUF20$INS_STAT2_I, levels=INS_STAT2_Ilevels, labels=INS_STAT2_Ilabels)
NISPUF20$ESTIAP20 <- factor(NISPUF20$ESTIAP20, levels=ESTIAPFlevels, labels=ESTIAPFlabels)

##########################################################################
# STEP 7:   CONTENTS AND STATISTICAL ESTIMATES(FREQUENCY) EXAMPLE        #
##########################################################################

#---CONTENTS---#
NISPUF20.CONTENTS <- contents(NISPUF20)$contents

print(NISPUF20.CONTENTS)

#IN CASE THAT THE R CONSOLE CANNOT DISPLAY WHOLE CONTENTS,
#YOU CAN SAVE CONTENTS INTO A FILE
write.table(NISPUF20.CONTENTS, file=paste(PUF,"/NIS",sep=""))

#---UNWEIGHTED FREQUENCY---#
unwt_freq <- function(UNWT.VAR){#FUNCTION TO PRINT UNWEIGHTED FREQUENCIES

unwt.tab <- wtd.table(UNWT.VAR, weights= NULL, type='table')
unwtd.freq <- data.frame(cbind(
unwt.tab, round(unwt.tab/sum(unwt.tab)*100,2),
cumsum(unwt.tab), cumsum(round(unwt.tab/sum(unwt.tab)*100,2))))
names(unwtd.freq) <- c("Frequency", "Percent", "Cumulative Frequency", "Cumulative Percent")
unwtd.title <- paste('2020 NIS-CHILD PUBLIC USE FILE', 'UNWEIGHTED FREQUENCIES', label(UNWT.VAR), sep="\n")
label(unwtd.freq) <- unwtd.title

print(unwtd.freq)
}

UNWT.VAR <- NISPUF20$AGEGRP	#INPUT A VARIABLE OF INTEREST
unwt_freq(UNWT.VAR)

#---WEIGHTED FREQUENCY---#
WT <- NISPUF20$RDDWT_C		#INPUT A WEIGHT VARIABLE
WT.VAR <- NISPUF20$AGEGRP 	#INPUT A VARIABLE OF INTEREST

wt.tab <- wtd.table(WT.VAR, weights= WT, type='table')
wtd.freq <- data.frame(cbind(
wt.tab, round(wt.tab/sum(wt.tab)*100,2),
cumsum(wt.tab), cumsum(round(wt.tab/sum(wt.tab)*100,2))))
names(wtd.freq) <- c("Frequency", "Percent", "Cumulative Frequency", "Cumulative Percent")
wtd.title <- paste('2020 NIS-CHILD PUBLIC USE FILE', 'WEIGHTED FREQUENCIES (EXCLUDING TERRITORIES)', label(WT.VAR), sep="\n")
label(wtd.freq) <- wtd.title

print(wtd.freq)

```


```{r}
#libraries
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(foreign)
library(tidyverse)
library(epitools)
library(lmtest)
library(tidyverse)
library(tidyr)
library(broom)
library(epiR)
library(dplyr)
library(dagitty)
library(ggdag)
```

##Subsetting the dataframe##
```{r}
finalproject <- NISPUF20 %>%
  select(c(1,2,12, 13, 14,23,25,26,29,30,33,34,40,41,45))

save

g <- dagitty("dag{
             x -> y;
             z2 -> y;
             w1 -> y;
             z1 -> y;
             w2 -> x;
             z2 <-> x;
             z2 -> w1;
             z1 -> w1;
             v -> w1
             v -> z1
             z2 -> w2;
             x [exposure];
             y [outcome]}")
dag(g)
dag  <- dagify(g, y ~ x + s, a, e, m,
  x ~ m,
  s ~ r,
  m ~ a,
  e ~ s, a, r,
  e ~~ x,
  exposure = "x",
  outcome = "y") %>%
ggplot(aes(x = x, y = y, xend = xend, yend = yend)) +
    geom_dag_point() +
    geom_dag_edges_arc() +
    geom_dag_text() +
    theme_dag()

ggdag(dag)
ggdag(dag) + theme_dag_blank()

```
